version: '3.8'

services:
  db:
    image: postgres
    shm_size: 128mb
    container_name: db
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ..
      dockerfile: config/Dockerfile
    container_name: api
    depends_on:
      - db
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - DB_DRIVER_NAME=${DB_DRIVER_NAME}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SSL_MODE=${SSL_MODE}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - MODE=${MODE}